apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4waiops-ibm-cp-waiops-catalog
spec:
  destination:
    namespace: cp4waiops
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cp4waiops/ibm-cp-waiops-catalog
    repoURL: https://github.com/gandhicloudlaborg/gan-sew-test17
    targetRevision: main
    helm:
      releaseName: ibm-cp-waiops-catalog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
